# permissions for end users to edit configmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-editor-role
rules:
- apiGroups:
  - custom.example.com
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom.example.com
  resources:
  - configmaps/status
  verbs:
  - get
